# 🚀 HFT-Ninja Minimal - MVP dla natychmiastowego działania
[package]
name = "hft-ninja-minimal"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }

[[bin]]
name = "hft-ninja-minimal"
path = "src/main.rs"
