version: '3.8'

services:
  # 🗄️ Database Services
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cerberus
      POSTGRES_USER: cerberus
      POSTGRES_PASSWORD: cerberus_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # 🔐 Security Services
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: cerberus_root_token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - ./config/vault:/vault/config
    command: vault server -dev -dev-listen-address=0.0.0.0:8200

  # 🧠 Core Services
  cerebro-bff:
    build:
      context: ./services/cerebro-bff
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HELIUS_API_KEY=${HELIUS_API_KEY:-demo}
      - QUICKNODE_RPC_URL=${QUICKNODE_RPC_URL:-https://api.devnet.solana.com}
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - qdrant

  hft-ninja:
    build:
      context: ./services/hft-ninja
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CEREBRO_BFF_URL=http://cerebro-bff:3000
      - HELIUS_WEBHOOK_SECRET=${HELIUS_WEBHOOK_SECRET:-demo}
    depends_on:
      - cerebro-bff

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  vault_data:
