# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hft-ninja"
    static_configs:
      - targets: ["hft-ninja:3000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "cerebro-bff"
    static_configs:
      - targets: ["cerebro-bff:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
