# 🐺 Projekt Cerberus Phoenix v2.0 - Cerebro-BFF Apko Manifest
# Ultralekki, bezpieczny obraz dla BFF i logiki AI

contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - wolfi-base
    - ca-certificates-bundle
    - tzdata
    - glibc-locale-en
    - libgcc
    - libstdc++
    - openssl
    - curl

# 🏗️ Build configuration
archs:
  - x86_64
  - aarch64

# 🔐 Security & Environment
environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  RUST_LOG: info
  RUST_BACKTRACE: 1

# 👤 User configuration
accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
      shell: /bin/sh
  run-as: 65532

# 🚀 Entrypoint
entrypoint:
  command: /usr/local/bin/cerebro-bff

# 🏷️ Annotations
annotations:
  org.opencontainers.image.title: "Cerberus Cerebro-BFF"
  org.opencontainers.image.description: "Ultralekki BFF z logiką AI i Context Engine"
  org.opencontainers.image.version: "2.0.0"
  org.opencontainers.image.authors: "SynergiaOS <202778732+SynergiaOS@users.noreply.github.com>"
  org.opencontainers.image.url: "https://github.com/SynergiaOS/Cerebros"
  org.opencontainers.image.source: "https://github.com/SynergiaOS/Cerebros"
  org.opencontainers.image.vendor: "Cerberus Phoenix Project"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.created: "2024-01-01T00:00:00Z"

# 🔒 Security labels
labels:
  "security.alpha.kubernetes.io/sysctls": "net.ipv4.ip_unprivileged_port_start=0"
  "security.alpha.kubernetes.io/unsafe-sysctls": ""
