# 🐺 Projekt Cerberus Phoenix v2.0 - Development Override
# Konfiguracja dla środowiska deweloperskiego

version: '3.8'

services:
  # 🥷 HFT-Ninja - Development Mode
  hft-ninja:
    build:
      context: ../services/hft-ninja
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ../services/hft-ninja/src:/app/src:ro
      - ../services/hft-ninja/Cargo.toml:/app/Cargo.toml:ro
    environment:
      RUST_LOG: debug
      SOLANA_RPC_URL: https://api.devnet.solana.com
      JITO_BLOCK_ENGINE_URL: https://mainnet.block-engine.jito.wtf
      CEREBRO_BFF_URL: http://cerebro-bff:8080
      DEV_MODE: "true"
    command: ["cargo", "watch", "-x", "run"]

  # 🧠 Cerebro-BFF - Development Mode
  cerebro-bff:
    build:
      context: ../services/cerebro-bff
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ../services/cerebro-bff/src:/app/src:ro
      - ../services/cerebro-bff/Cargo.toml:/app/Cargo.toml:ro
    environment:
      RUST_LOG: debug
      QDRANT_URL: http://qdrant:6333
      FINLLAMA_API_URL: http://host.docker.internal:11434
      DEEPSEEK_API_URL: http://host.docker.internal:11435
      DEV_MODE: "true"
    command: ["cargo", "watch", "-x", "run"]

  # 🖥️ Dashboard - Development Mode
  dashboard:
    build:
      context: ../services/dashboard
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ../services/dashboard/app:/app/app:ro
      - ../services/dashboard/package.json:/app/package.json:ro
      - ../services/dashboard/package-lock.json:/app/package-lock.json:ro
      - ../services/dashboard/next.config.js:/app/next.config.js:ro
      - ../services/dashboard/tailwind.config.js:/app/tailwind.config.js:ro
      - ../services/dashboard/tsconfig.json:/app/tsconfig.json:ro
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8080
      NEXT_PUBLIC_NINJA_URL: http://localhost:8081
      WATCHPACK_POLLING: "true"
    command: ["npm", "run", "dev"]

  # 🧠 Local LLM Server (FinLlama)
  finllama:
    image: ollama/ollama:latest
    container_name: cerberus-finllama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - finllama_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0
    networks:
      - cerberus-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # 🧮 Local Math LLM Server (Deepseek-Math)
  deepseek-math:
    image: ollama/ollama:latest
    container_name: cerberus-deepseek-math
    restart: unless-stopped
    ports:
      - "11435:11434"
    volumes:
      - deepseek_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0
    networks:
      - cerberus-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # 📊 Development Tools
  redis:
    image: redis:7-alpine
    container_name: cerberus-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cerberus-net

  # 🔍 Elasticsearch (for development search)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: cerberus-elasticsearch-dev
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - cerberus-net

volumes:
  finllama_data:
  deepseek_data:
